export const actionTypes = {
    CATEGORY_SELECTED: 'CATEGORY_SELECTED',

    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',

    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    NOTIFICATION_COUNTER: 'NOTIFICATION_COUNTER',
    CHANGE_CURRENCY: 'CHANGE_CURRENCY',

    TOTAL_PRICE_AND_CART_ITEM_COUNT: 'TOTAL_PRICE_AND_CART_ITEM_COUNT',
    INCREASE_ITEM_QUANTITY: 'INCREASE_ITEM_QUANTITY',
    DECREASE_ITEM_QUANTITY: 'DECREASE_ITEM_QUANTITY',
};
